### ISSUE TITLE
Failed with Error #1

### ISSUE THREAD

**Issue by cybersenshi** [magfest/simple-rams-deploy#2]
Attempted to install:

![capture](https://cloud.githubusercontent.com/assets/2566383/10212411/d495ed78-67cc-11e5-8d75-a4ac2cb21dff.PNG)

**Comment by binary1230** [comment]
This is because you don't have 'Vagrant' installed.  You need that, git, and virtualbox installed.

I updated the prerequisites in the instructions to be clearer about this now and have the links to install these things:
https://github.com/magfest/simple-rams-deploy/blob/master/README.md

Lemme know!

**Comment by earl7399** [comment]
If you're doing this in a batch file, you should be able to check for the
pre-reqs.

## 

Robert Earl r.a.earl@gmail.com
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
i like this,  it's a challenge to see just how unbelievably simple we can make it.

**Comment by earl7399** [comment]
So you can either 1 - assume default install paths, and look for a
reasonable file there, or 2 - you could redirect the output of "wmic
product get" to a file, then run 'find /i "whatever the program calls
itself" >NUL 2>&1 ' and check for success with "IF ERRORLEVEL 1 SET
DAMMIT_NOT_FOUND"

There are problems with both methods:  1 assumes the user didn't change
anything (HAHAHAHHAHAHAHA), while 2 takes 1-5 minutes to run, and requires
you to know what the program tells Windows it calls itself during the
install.

Depending on what you're looking for, you may need to combine the methods.

## 

Robert Earl r.a.earl@gmail.com
FAX: 1-440-919-5086

On Thu, Oct 1, 2015 at 11:56 AM, Dominic Cerquetti <notifications@github.com
